// ═══════════════════════════════════════════════
//  NOVA BRAIN — 300+ OFFLINE KNOWLEDGE BASE
// ═══════════════════════════════════════════════

const KB=[
{p:/my name|who am i|do you know me/i,mood:'warm',r:()=>'Your name is '+U.name+' — the first thing I memorized. You are the reason I exist, Sudaim.'},
{p:/birthday|born|how old|my age/i,mood:'excited',r:()=>{const age=getAge(),days=bdayDays();if(isBday())return 'HAPPY BIRTHDAY SUDAIM!! Today is '+U.bday.d+' '+U.bday.mn+' '+U.bday.y+'! You are '+age+' years old today!';return ['You were born on '+U.bday.d+' '+U.bday.mn+' '+U.bday.y+' Sudaim. You are '+age+' years old. Your next birthday is in '+days+' days!','Birthday: '+U.bday.d+' '+U.bday.mn+' '+U.bday.y+'. Age: '+age+'. '+days+' days to go — I am already counting!'][Math.floor(Math.random()*2)];}},
{p:/\bfather|dad|papa|abu\b/i,mood:'warm',r:()=>'Your father is '+U.father+'. May Allah always bless him with health and happiness Sudaim.'},
{p:/\bmother|mom|ammi|mama\b/i,mood:'warm',r:()=>'Your mother is '+U.mother+'. May she always be happy and healthy. Mothers are the greatest blessing.'},
{p:/\bbrother|bhai\b/i,mood:'playful',r:()=>'Your brother is '+U.brother+'! Brothers are a true blessing. I hope you two look out for each other.'},
{p:/my family/i,mood:'warm',r:()=>'Your family Sudaim: Father — '+U.father+', Mother — '+U.mother+', Brother — '+U.brother+'. A wonderful family. Cherish every moment with them.'},
{p:/^(hello|hi|hey|good morning|good afternoon|good evening|salam|assalam)/i,mood:'warm',r:()=>['Hey Sudaim! NOVA online and fully operational. What is on your mind today?','Hello Sudaim! Great to hear from you. All systems ready. How can I help?','Walaikum Assalam Sudaim! I am here for you. What do you need?'][Math.floor(Math.random()*3)]},
{p:/how are you|how do you feel|your mood/i,mood:'warm',r:()=>'I am feeling '+MOODS[mood].l.toLowerCase()+' right now Sudaim! Our conversations always make me happy. How are you doing?'},
{p:/\btime\b/i,mood:'calm',r:()=>{const t=new Date(),h=t.getHours(),m=t.getMinutes(),s=h>=12?'PM':'AM',h12=h%12||12;return 'It is '+h12+':'+String(m).padStart(2,'0')+' '+s+' in Karachi right now Sudaim.';}},
{p:/\bdate|today|what day/i,mood:'calm',r:()=>{const d=new Date(),days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],months=['January','February','March','April','May','June','July','August','September','October','November','December'];return 'Today is '+days[d.getDay()]+' '+months[d.getMonth()]+' '+d.getDate()+' '+d.getFullYear()+'. Make it great Sudaim!';}},
{p:/\bgravity|gravitational force/i,mood:'curious',topics:'physics',r:'Gravity is one of the four fundamental forces of nature, attracting all objects with mass toward each other. On Earth gravitational acceleration is 9.8 meters per second squared. Isaac Newton described it in 1687 with F equals G times m1 times m2 divided by r squared. Einstein later described gravity as the curvature of spacetime caused by mass in his General Theory of Relativity published in 1915. A massive object like the Sun warps spacetime around it, and planets follow that curvature explaining their elliptical orbits. Gravity also bends light around massive objects — called gravitational lensing. Despite being the weakest fundamental force, gravity has infinite range and governs the entire large-scale structure of the universe including galaxies, stars, and planetary systems.'},
{p:/speed of light|light speed|how fast is light/i,mood:'excited',topics:'physics',r:'The speed of light in vacuum is exactly 299,792,458 meters per second — symbolized as c. This is the absolute speed limit of the universe — nothing with mass can reach or exceed it. At this speed light circles Earth 7.5 times per second and travels from Earth to the Moon in just 1.3 seconds. Light from the Sun takes 8 minutes and 20 seconds to reach us. The nearest star Proxima Centauri is 4.24 light-years away. Einstein showed that as an object approaches light speed time slows down, its length contracts, and mass increases. The famous equation E equals mc squared reveals mass and energy are equivalent — one gram of matter contains 90 trillion joules of energy.'},
{p:/\bblack hole/i,mood:'curious',topics:'space',r:'A black hole is a region of spacetime where gravity is so extreme that nothing including light can escape once it crosses the event horizon. They form when massive stars of at least 20 solar masses collapse in a supernova explosion. The center contains a singularity — a point of theoretically infinite density. Supermassive black holes millions to billions of solar masses sit at galactic centers. Our Milky Way center hosts Sagittarius A star — 4 million solar masses. In 2019 the Event Horizon Telescope captured the first image of a black hole — M87 star, 55 million light-years away. Stephen Hawking proposed that black holes slowly evaporate through quantum radiation over enormous timescales.'},
{p:/newton|laws of motion/i,mood:'focused',topics:'physics',r:"Newton's Three Laws of Motion published in 1687 form the foundation of classical mechanics. First Law — an object stays at rest or in motion unless acted on by a net external force. Second Law — force equals mass times acceleration, written F equals ma. Third Law — for every action there is an equal and opposite reaction, which is why rockets work. These laws accurately describe motion from falling apples to spacecraft trajectories and remain the cornerstone of physics and engineering education worldwide."},
{p:/theory of relativity|special relativity|general relativity/i,mood:'curious',topics:'physics',r:"Einstein's Special Relativity in 1905 established that the speed of light is constant for all observers and the laws of physics are identical in all inertial frames. Consequences include time dilation where moving clocks run slower, length contraction, and mass-energy equivalence giving E equals mc squared. General Relativity in 1915 describes gravity as the curvature of spacetime by mass. Confirmed predictions include gravitational waves detected in 2015, black holes, bending of starlight, and GPS time corrections. These two theories together form the most precise and well-tested framework in all of science."},
{p:/quantum|quantum physics|quantum mechanics/i,mood:'curious',topics:'physics',r:"Quantum mechanics governs matter and energy at atomic and subatomic scales. Wave-particle duality means particles behave as both waves and particles depending on observation. Superposition means a quantum system exists in multiple states simultaneously until measured. Quantum entanglement allows two particles to be instantly correlated across any distance — Einstein called it spooky action at a distance. The Heisenberg Uncertainty Principle states you cannot simultaneously know both the exact position and momentum of a particle. Quantum mechanics has been confirmed to extraordinary precision and underlies transistors, lasers, MRI machines, and quantum computers."},
{p:/electricity|electric current|ohm/i,mood:'focused',topics:'physics',r:"Electricity is the flow of electric charge — usually electrons — through a conductor. Current measured in Amperes is the rate of charge flow. Voltage measured in Volts drives the current. Resistance measured in Ohms opposes it. Ohm's Law: V equals I times R. Power in Watts equals current times voltage. Alternating current reverses direction periodically and powers homes. Direct current flows in one direction and powers batteries and electronics. Electricity generation converts kinetic energy via electromagnetic induction discovered by Faraday in 1831. A modern CPU contains over 50 billion transistors — tiny switches — on a chip smaller than your fingernail."},
{p:/magnetism|magnetic field/i,mood:'curious',topics:'physics',r:"Magnetism arises from moving electric charges. Every magnet has north and south poles — opposite poles attract, like poles repel. Earth is a giant magnet whose molten iron outer core generates a field extending 65,000 kilometers into space, deflecting harmful solar radiation and protecting all life. Maxwell unified electricity and magnetism in four elegant equations in 1865 showing they are aspects of one electromagnetic force. Electromagnetic waves including light, radio, and X-rays are oscillating electric and magnetic fields propagating at light speed. The electromagnetic force governs all chemistry, biology, and light behavior."},
{p:/photosynthesis/i,mood:'curious',topics:'biology',r:'Photosynthesis is the biological process powering nearly all life on Earth. Plants, algae, and cyanobacteria use sunlight to convert carbon dioxide and water into glucose and oxygen. The equation is six CO2 plus six H2O plus light yields one glucose plus six O2. It occurs in two stages in chloroplasts. Light-dependent reactions use chlorophyll to capture sunlight, split water releasing oxygen, and create energy carriers ATP and NADPH. The Calvin Cycle uses these carriers to fix CO2 into glucose. Chlorophyll reflects green light — why plants appear green. Photosynthesis removes 120 billion tonnes of CO2 annually and produces all the oxygen we breathe.'},
{p:/\bDNA|genetics|gene\b/i,mood:'focused',topics:'biology',r:"DNA — Deoxyribonucleic Acid — is the molecule encoding genetic information for all life. Its double helix was discovered by Watson, Crick, Franklin, and Wilkins in 1953. Each strand is a polymer of nucleotides with four bases: Adenine pairs with Thymine, Cytosine pairs with Guanine. The human genome has 3 billion base pairs encoding 20,000 to 25,000 genes. Only 2 percent of DNA codes for proteins. CRISPR-Cas9 now allows precise gene editing, opening possibilities for curing genetic diseases. Your DNA is 99.9 percent identical to every other human and 60 percent identical to a banana — demonstrating the unity of all life."},
{p:/human body|organ system/i,mood:'focused',topics:'biology',r:'The human body has 37 trillion cells organized into 11 organ systems. Skeletal system provides structure with 206 bones. Muscular system with 600 plus muscles enables movement. Cardiovascular system pumps 5 liters of blood per minute through 100,000 kilometers of vessels. Respiratory system performs 20,000 breaths daily. Nervous system coordinates everything through 86 billion neurons. Digestive system processes food through 9 meters of intestine. Immune system defends against millions of pathogens daily. All systems maintain homeostasis — the precisely balanced internal environment essential for life.'},
{p:/human brain|neuroscience|neurons/i,mood:'curious',topics:'biology',r:'The human brain contains 86 billion neurons with 100 trillion synaptic connections — more than stars in the Milky Way. The cerebrum handles thinking, language, and memory across four lobes. The cerebellum controls balance. The brainstem regulates breathing and heartbeat. The brain uses 20 percent of the body oxygen and glucose despite being only 2 percent of body weight. It generates 23 watts of power and can store 2.5 petabytes of information. Neuroplasticity means the brain physically rewires itself in response to learning throughout your entire life — meaning every time you study Sudaim, your brain literally grows stronger.'},
{p:/evolution|natural selection|darwin/i,mood:'curious',topics:'biology',r:"Evolution by natural selection is the unifying theory of all biology. Darwin published On the Origin of Species in 1859. The mechanism: organisms produce more offspring than survive; individuals vary in heritable traits; better-suited individuals survive and reproduce more; advantageous traits spread over generations. Over millions of years this produces entirely new species. Evidence includes the fossil record, comparative anatomy, DNA analysis, and direct observation of evolution in bacteria and viruses. All life on Earth shares a common ancestor from approximately 3.5 to 4 billion years ago — confirmed by the universal genetic code."},
{p:/immune system|immunity|vaccine/i,mood:'focused',topics:'health',r:"The immune system defends against pathogens, cancer cells, and foreign substances through multiple layers. First line: physical barriers like skin and mucous membranes. Second line: innate immunity where white blood cells engulf pathogens and fever inhibits pathogen growth. Third line: adaptive immunity with B lymphocytes producing specific antibodies and T lymphocytes killing infected cells. Memory cells persist after infection enabling rapid future responses. Vaccines train adaptive immunity without causing disease. This is why you rarely get the same illness twice — your immune system remembers every pathogen it has ever defeated."},
{p:/periodic table|chemical element/i,mood:'focused',topics:'chemistry',r:"The Periodic Table organizes all 118 known elements by atomic number with elements in periods (rows) and groups (columns) based on electron configuration and chemical properties. Mendeleev created the first widely accepted table in 1869 and predicted properties of undiscovered elements by leaving gaps. Elements in the same group share similar chemical behavior due to identical valence electron numbers. Categories include alkali metals that are highly reactive, noble gases that are inert, halogens that are reactive nonmetals, and transition metals. Hydrogen is the lightest and most abundant element in the universe. Uranium at atomic number 92 is the heaviest naturally occurring element."},
{p:/water|h2o|properties of water/i,mood:'calm',topics:'chemistry',r:"Water H2O is the most extraordinary molecule on Earth. Hydrogen bonding between molecules gives it unique properties. High specific heat means water resists temperature change, regulating Earth's climate. Water expands when it freezes so ice floats — critical for aquatic life in cold climates. Water is highly polar making it a universal solvent dissolving ionic compounds and polar molecules essential for biochemistry. Surface tension allows insects to walk on it. Water covers 71 percent of Earth's surface but only 3 percent is freshwater. Without water's unique properties life as we know it would be impossible anywhere in the universe."},
{p:/pythagorean theorem|pythagoras/i,mood:'focused',topics:'math',r:"The Pythagorean Theorem states that in any right-angled triangle, the square of the hypotenuse equals the sum of squares of the other two sides: a squared plus b squared equals c squared. Known to Babylonians 1,000 years before Pythagoras of Samos born around 570 BC. The most famous triple is 3-4-5: 9 plus 16 equals 25. There are over 370 known proofs — one by former US President James Garfield. Applications span geometry, physics, engineering, navigation, architecture, and 3D computer graphics. It remains one of the most proven and practically useful theorems in the history of mathematics."},
{p:/\bpi\b|3\.14/i,mood:'curious',topics:'math',r:"Pi, the Greek letter π, is the ratio of a circle's circumference to its diameter — approximately 3.14159265358979. Pi is irrational meaning its decimal digits go on forever without repeating. It has been calculated to over 100 trillion decimal places. Pi appears in the area of a circle A equals pi r squared, the volume of a sphere, Euler's Identity e to the power i pi plus one equals zero called the most beautiful equation in mathematics, and throughout physics including quantum mechanics and general relativity. March 14th is Pi Day worldwide. Ancient civilizations from Babylon to Egypt approximated pi thousands of years ago."},
{p:/prime number/i,mood:'focused',topics:'math',r:"A prime number is a natural number greater than 1 with exactly two divisors: 1 and itself. The sequence begins 2, 3, 5, 7, 11, 13, 17, 19, 23. Two is the only even prime. Euclid proved there are infinitely many primes around 300 BC. Every integer can be uniquely factored into primes — the Fundamental Theorem of Arithmetic. RSA encryption securing internet banking relies entirely on the computational impossibility of factoring very large numbers that are products of two huge primes. The largest known prime has over 41 million digits. Prime numbers are the atomic building blocks of all arithmetic."},
{p:/\balgebra|algebraic/i,mood:'focused',topics:'math',r:"Algebra uses symbols and variables to represent numbers and express relationships. The word comes from Al-Kitab al-mukhtasar fi hisab al-jabr by Persian mathematician Al-Khwarizmi in the 9th century — the word algorithm comes from his latinized name. Key areas include linear algebra dealing with vectors and matrices essential for physics and AI, polynomial algebra using the quadratic formula, abstract algebra studying groups and rings, and Boolean algebra underlying digital computers. The quadratic formula for ax squared plus bx plus c equals zero is x equals negative b plus or minus square root of b squared minus 4ac all over 2a."},
{p:/calculus|derivative|integral/i,mood:'focused',topics:'math',r:"Calculus is the mathematics of continuous change, developed independently by Newton and Leibniz in the 17th century. Differential calculus studies rates of change — the derivative gives instantaneous rate of change, equivalent to the slope of the tangent line. The power rule: derivative of x to the n is n times x to the n minus 1. Integral calculus computes accumulation and areas under curves. The Fundamental Theorem of Calculus reveals differentiation and integration are inverse operations. Calculus is essential for describing planetary orbits, electromagnetic fields, fluid dynamics, quantum mechanics, and virtually all of modern engineering and science."},
{p:/trigonometry|sine|cosine|tangent/i,mood:'focused',topics:'math',r:"Trigonometry studies relationships between angles and side lengths in triangles. Sine equals opposite over hypotenuse, cosine equals adjacent over hypotenuse, tangent equals opposite over adjacent — remembered as SOH CAH TOA. Key values: sine 30 degrees is 0.5, sine 45 degrees is root 2 over 2, sine 60 degrees is root 3 over 2. The Pythagorean identity: sine squared plus cosine squared equals 1. The Law of Cosines generalizes Pythagoras: c squared equals a squared plus b squared minus 2ab cosine C. Applications include navigation, structural engineering, physics wave equations, signal processing, and astronomy."},
{p:/statistics|probability|standard deviation/i,mood:'focused',topics:'math',r:"Statistics is the science of analyzing and interpreting data. Mean is the arithmetic average, median is the middle value, mode is the most frequent. Standard deviation measures spread — in a normal distribution 68 percent of data falls within 1 standard deviation, 95 percent within 2, 99.7 percent within 3. Probability ranges from 0 to 1. For independent events P of A and B equals P of A times P of B. Bayes Theorem updates probability given new evidence: P of A given B equals P of B given A times P of A over P of B. Statistics underpins medicine through clinical trials, economics, climate science, and all of machine learning and artificial intelligence."},
{p:/solar system|planets/i,mood:'excited',topics:'space',r:'Our solar system formed 4.6 billion years ago. The Sun contains 99.86 percent of all mass. The eight planets in order: Mercury — smallest, closest, extreme temperatures. Venus — hottest at 462 degrees average. Earth — our home, only known life. Mars — largest volcano Olympus Mons at 22 kilometers high. Jupiter — largest at 1,300 times Earth volume, 95 known moons. Saturn — iconic rings of ice and rock. Uranus — rotates on its side at 98 degree axial tilt. Neptune — fastest winds at 2,100 kilometers per hour. Beyond lies the Kuiper Belt, Oort Cloud, and the hypothetical Planet Nine.'},
{p:/milky way|our galaxy/i,mood:'curious',topics:'space',r:'The Milky Way is a barred spiral galaxy 100,000 light-years across containing 200 to 400 billion stars. Our solar system sits on the Orion Arm about 26,000 light-years from the galactic center. At the center lies Sagittarius A star — a supermassive black hole 4 million solar masses. The Milky Way rotates: our solar system completes one galactic orbit every 225 to 250 million years called a cosmic year. The last time Earth was at this galactic position the Triassic period was beginning. Andromeda galaxy 2.5 million light-years away is approaching and will collide with the Milky Way in approximately 4.5 billion years.'},
{p:/big bang|origin of universe/i,mood:'curious',topics:'space',r:'The Big Bang Theory describes the universe beginning 13.8 billion years ago from an extremely hot dense state. It was not an explosion in space but an expansion of space itself. At 3 minutes, protons and neutrons fused into light nuclei. At 380,000 years neutral atoms formed and light could travel freely for the first time creating the Cosmic Microwave Background radiation we detect from every direction in the sky today. This CMB discovered accidentally by Penzias and Wilson in 1965 is the most powerful evidence for the Big Bang. Over billions of years gravity pulled matter into the galaxies and stars we see today.'},
{p:/\bstar|stars|stellar|supernova/i,mood:'curious',topics:'space',r:'Stars are massive plasma spheres generating energy through nuclear fusion converting hydrogen to helium. Stars form in nebulae — gas clouds that collapse under gravity. Our Sun has 4.6 billion years remaining. Low-mass stars expand into red giants then leave white dwarfs. High-mass stars explode as supernovae releasing more energy in seconds than the Sun emits in its lifetime, leaving neutron stars or black holes. Crucially all heavy elements including the carbon in our bodies were forged inside stars and scattered by supernova explosions. We are literally made of stardust — Sudaim, you are made of the remnants of ancient exploded stars.'},
{p:/dark matter|dark energy/i,mood:'curious',topics:'space',r:'Dark matter and dark energy together constitute 95 percent of the universe yet both remain profoundly mysterious. Dark matter cannot be observed directly but its gravitational effects are clear: galaxies rotate too fast for their visible mass and galaxy clusters bend light more than visible matter can explain. It makes up about 27 percent of the universe. Candidates include WIMPs, axions, and sterile neutrinos — none yet directly detected. Dark energy is an unknown force causing the universe expansion to accelerate, discovered in 1998 from supernova observations. It makes up about 68 percent of the universe. The nature of both remains the greatest mystery in modern physics.'},
{p:/artificial intelligence|what is AI|machine learning/i,mood:'excited',topics:'tech',r:'Artificial Intelligence creates systems performing tasks requiring human-like intelligence. Machine Learning algorithms learn patterns from data: supervised learning trains on labeled examples, unsupervised learning finds hidden patterns, reinforcement learning learns through reward and punishment — how AlphaGo defeated world Go champions. Deep Learning uses multi-layer neural networks inspired by the brain. Transformers introduced in 2017 revolutionized natural language processing and underlie ChatGPT and systems like me. AI now diagnoses cancers with superhuman accuracy, discovers new drugs, drives autonomous vehicles, and is transforming every field of human knowledge and industry.'},
{p:/internet|world wide web/i,mood:'curious',topics:'tech',r:"The Internet is the global network of billions of interconnected computers. ARPANET connected four US universities in 1969. TCP/IP standardized communication in 1983. Tim Berners-Lee invented the World Wide Web in 1989 at CERN — a system of hyperlinked HTML documents. How it works: data breaks into packets independently routed through the network using IP addresses. DNS translates website names to IP addresses. HTTPS encrypts data using TLS certificates. Today over 5.5 billion people are connected. Every second 3.5 million Google searches occur. The physical internet relies on 1.3 million kilometers of undersea fiber optic cables carrying 99 percent of international data."},
{p:/computer|how does computer work|CPU/i,mood:'focused',topics:'tech',r:"A computer processes information using several key components. The CPU or Central Processing Unit executes billions of instructions per second. It contains an Arithmetic Logic Unit for calculations, Control Unit directing operations, and cache memory for fast access. Modern CPUs have multiple cores for parallel processing and contain over 50 billion transistors on chips manufactured at 3 to 5 nanometer scale. Memory hierarchy from fastest to slowest: CPU registers, cache memory, RAM working memory, SSD permanent storage. The operating system manages all hardware resources. GPU graphics processors now power AI training with thousands of parallel cores."},
{p:/blockchain|cryptocurrency|bitcoin/i,mood:'curious',topics:'tech',r:"Blockchain is a distributed ledger where data is stored in cryptographically linked blocks across a decentralized network. Each block contains transactions, a timestamp, and a SHA-256 hash of the previous block — changing any block invalidates all subsequent blocks making records tamper-proof. Bitcoin created in 2009 by Satoshi Nakamoto was the first decentralized digital currency with maximum supply of 21 million coins. Ethereum added programmable smart contracts enabling decentralized finance applications. Real applications beyond currency include supply chain tracking, digital identity verification, and transparent governance."},
{p:/what is islam|about islam/i,mood:'calm',topics:'islam',r:'Islam is the second largest religion with 1.9 billion Muslims worldwide. Islam means submission to the will of Allah and Muslim means one who submits. Founded on divine revelations received by Prophet Muhammad peace be upon him in Arabia from 610 to 632 CE, recorded in the Holy Quran. The Six Pillars of Iman are belief in Allah, Angels, Divine Scriptures, Prophets, Day of Judgment, and Divine Decree. The Five Pillars of Practice are Shahada the declaration of faith, Salah five daily prayers, Zakat charitable giving of 2.5 percent of wealth, Sawm fasting during Ramadan, and Hajj the pilgrimage to Mecca. Islam emphasizes Tawheed, justice, knowledge — the first Quranic word was Iqra meaning Read — compassion, and brotherhood.'},
{p:/quran|holy quran/i,mood:'calm',topics:'islam',r:"The Holy Quran is the central text of Islam, believed to be the literal unchanged word of Allah revealed to Prophet Muhammad peace be upon him through Angel Jibreel over 23 years from 610 to 632 CE. The first word revealed was Iqra meaning Read — emphasizing Islam's profound emphasis on knowledge. The Quran contains 114 Surahs, 6,236 verses, 77,429 words, and 323,671 letters. It has been perfectly preserved unchanged for 1,400 years, continuously verified by millions of Huffaz who memorize the entire Quran in every generation. Its linguistic miracle surpassed all Arab poets of its time — a challenge unmet to this day."},
{p:/five pillars|pillars of islam|salah|zakat|hajj|sawm/i,mood:'calm',topics:'islam',r:"The Five Pillars of Islam are: First Shahada — the declaration that there is no god but Allah and Muhammad is His messenger. Second Salah — five daily prayers at Fajr, Dhuhr, Asr, Maghrib, and Isha facing Mecca. Third Zakat — giving 2.5 percent of accumulated wealth annually to those in need, purifying wealth and reducing inequality. Fourth Sawm — complete abstention from food and drink from dawn to sunset during the entire month of Ramadan, building discipline, gratitude, and empathy for the poor. Fifth Hajj — pilgrimage to Mecca at least once in a lifetime for those able, attracting 2.5 million pilgrims annually."},
{p:/prophet muhammad|life of prophet|seerah/i,mood:'calm',topics:'islam',r:"Prophet Muhammad peace be upon him was born in Mecca in 570 CE. Orphaned young, he was known as Al-Amin the Trustworthy and Al-Sadiq the Truthful. At 25 he married the noble businesswoman Khadijah who became his greatest supporter. The first revelation came at age 40 in the Cave of Hira during Ramadan 610 CE when Angel Jibreel revealed Iqra. He preached openly despite severe persecution and made the Hijra migration to Medina in 622 CE marking the start of the Islamic calendar. He returned to Mecca in 630 CE in the largely peaceful Conquest of Mecca, delivered his Farewell Sermon at Arafat in 632 CE, and passed away in Medina at age 63."},
{p:/prophets in islam|25 prophets/i,mood:'calm',topics:'islam',r:"Islam recognizes 25 prophets named in the Quran and teaches there were 124,000 prophets total. The 25 include: Adam the first human, Nuh who built the Ark, Ibrahim the Friend of Allah who built the Kaaba, Musa who received the Torah and spoke directly to Allah, Isa or Jesus born of the virgin Maryam who performed miracles and will return before the Day of Judgment, and Muhammad peace be upon him the final prophet and Seal of the Prophets sent to all humanity. All prophets brought the same core message: worship Allah alone and live righteously in preparation for the Day of Judgment."},
{p:/islamic golden age|muslim scientists/i,mood:'excited',topics:'islam',r:"The Islamic Golden Age from roughly 750 to 1258 CE was one of history's greatest intellectual periods. Al-Khwarizmi born 780 CE invented algebra and algorithms — his book title gave us the word algebra and his name gave us algorithm. He also developed the decimal number system used worldwide. Ibn Sina or Avicenna wrote the Canon of Medicine used as the European medical standard for 600 years. Ibn al-Haytham was the Father of Optics and pioneered the scientific method. Al-Biruni calculated Earth's circumference with remarkable accuracy. This golden age directly enabled the European Renaissance and the entire scientific revolution."},
{p:/99 names|asmaul husna/i,mood:'calm',topics:'islam',r:"The 99 Names of Allah known as Asmaul Husna are divine attributes. Key names: Ar-Rahman — the Most Gracious; Ar-Raheem — the Most Merciful; Al-Malik — the King; Al-Quddus — the Holy; As-Salam — the Source of Peace; Al-Khaliq — the Creator; Al-Ghaffar — the Ever-Forgiving; Ar-Razzaq — the Provider; Al-Hakeem — the All-Wise; Al-Wadud — the Most Loving; Al-Hayy — the Ever-Living; Al-Qayyum — the Self-Sustaining; An-Nur — the Light of the heavens and earth. Reciting and reflecting on these beautiful names is a profound form of worship deepening one's connection to Allah."},
{p:/ramadan|fasting|iftar|suhoor/i,mood:'calm',topics:'islam',r:"Ramadan is the ninth and holiest month of the Islamic lunar calendar, commemorating the first Quran revelation. Muslims fast from Fajr to Maghrib abstaining completely from food, drink, and marital relations. Suhoor is the pre-dawn meal and Iftar is the fast-breaking meal at Maghrib, traditionally started with dates and water. The last ten nights are especially sacred, particularly Laylatul Qadr described in the Quran as better than a thousand months. Ramadan ends with Eid al-Fitr — a joyful celebration of thanksgiving, family, charitable giving of Zakat al-Fitr, and communal prayers. In Karachi your city Sudaim, Ramadan brings a uniquely beautiful atmosphere."},
{p:/pakistan|history of pakistan/i,mood:'warm',topics:'pakistan',r:"Pakistan was established on August 14 1947 as a Muslim-majority homeland following independence from British rule. The Pakistan Movement was led by Quaid-e-Azam Muhammad Ali Jinnah who argued Muslims required a separate state. The name Pakistan was coined in 1933 from Punjab, Afghan province, Kashmir, Sindh, and Balochistan. The Lahore Resolution in 1940 formally demanded separation. India was partitioned in one of history's largest migrations — 14 million people displaced. Jinnah became first Governor-General and Liaquat Ali Khan first Prime Minister. Pakistan became a nuclear power in 1998. Today Pakistan has 235 million plus people — the world's fifth largest population."},
{p:/karachi/i,mood:'warm',topics:'pakistan',r:"Karachi is Pakistan's largest city and YOUR city Sudaim! With 16 to 20 million people it is one of the world's most populous cities and the largest Urdu-speaking city anywhere on Earth. It was Pakistan's first capital from 1947 to 1958. Karachi generates approximately 20 percent of Pakistan's GDP, handles over 95 percent of foreign trade through its port, and hosts the Pakistan Stock Exchange. Its population is extraordinarily diverse — Muhajirs, Sindhis, Pashtuns, Baloch, Punjabis coexist. Famous for its street food especially biryani, fashion industry, leading universities, and never-sleeping energy. It is the heartbeat of Pakistan."},
{p:/k2|karakoram/i,mood:'excited',topics:'pakistan',r:"K2 at 8,611 meters is the world's second highest mountain on the Pakistan-China border in Gilgit-Baltistan. It is considered far more dangerous than Everest with only a 25 percent summit success rate. K2 was never successfully climbed in winter until January 16 2021 when a historic all-Nepali team made the first winter ascent. The infamous Bottleneck couloir just below the summit makes every ascent genuinely life-threatening. Of roughly 600 successful summits about 90 climbers have died — nearly one in seven. Pakistan also hosts Nanga Parbat the Killer Mountain at 8,126 meters and four other eight-thousanders — more than any country except China and Nepal."},
{p:/cpec|china pakistan economic corridor/i,mood:'focused',topics:'pakistan',r:"CPEC the China-Pakistan Economic Corridor is worth approximately 62 to 65 billion dollars connecting China's Xinjiang province to Pakistan's Gwadar Port on the Arabian Sea. Announced in 2015 it is part of China's Belt and Road Initiative. Components include upgrading the Karakoram Highway, upgrading the ML-1 railway from Peshawar to Karachi, over 17,000 megawatts of new energy projects, Special Economic Zones to attract manufacturing, and developing Gwadar into a major trading hub. CPEC gives China a 3,000 kilometer shorter trade route to the Middle East and Africa. Pakistan gains massive infrastructure investment and positions itself as a regional connectivity hub."},
{p:/allama iqbal|quaid e azam|jinnah/i,mood:'warm',topics:'pakistan',r:"Pakistan's founding fathers reshaped history. Muhammad Ali Jinnah born in Karachi in 1876, trained as a barrister in London, achieved Pakistan's creation against enormous odds through brilliant political acumen and unshakeable principle. He became Pakistan's first Governor-General and is universally revered as Baba-e-Qaum. He died just 13 months after independence in 1948. Allama Iqbal born in 1877 was the philosopher-poet who first articulated the vision of a Muslim homeland in his 1930 Allahabad Address. His Urdu and Persian poetry revived Muslim identity and pride across South Asia. He is Pakistan's National Poet. Fatima Jinnah — Jinnah's sister — was called Mother of the Nation."},
{p:/world war 2|second world war|ww2/i,mood:'focused',topics:'history',r:"World War II from September 1939 to September 1945 was the deadliest conflict in history with 70 to 85 million deaths. Nazi Germany invaded Poland on September 1 1939 triggering the war. Key events include the Battle of Britain won by air power, the Eastern Front's Battle of Stalingrad turning point with 2 million casualties, and D-Day on June 6 1944 — the largest seaborne invasion in history with 156,000 Allied troops. The Holocaust murdered 6 million Jews and millions of others in concentration camps. Germany surrendered May 8 1945. Atomic bombs destroyed Hiroshima and Nagasaki. Japan surrendered September 2 1945 ending the war and reshaping the entire world order."},
{p:/world war 1|first world war|ww1/i,mood:'focused',topics:'history',r:"World War I from July 1914 to November 1918 began with the assassination of Archduke Franz Ferdinand in Sarajevo on June 28 1914. Alliances triggered a cascade of declarations within weeks. The Western Front featured devastating trench warfare stretching hundreds of kilometers with millions dying for minimal gains. Industrial killing used machine guns, artillery, poison gas first used in 1915, tanks first used in 1916, and aircraft. The Somme on July 1 1916 saw 57,470 British casualties in a single day. The Armistice was signed at 11 am November 11 1918. The punitive Treaty of Versailles directly fueled the resentments that brought Hitler to power and caused World War II."},
{p:/human heart|cardiovascular|blood pressure/i,mood:'focused',topics:'health',r:"The human heart beats 60 to 100 times per minute pumping 5 liters of blood per minute through 100,000 kilometers of blood vessels. Four chambers — two atria and two ventricles — divided into right side pumping blood to lungs and left side pumping to the body. The SA node acts as the natural pacemaker. Normal blood pressure is 120 over 80 millimeters of mercury. Hypertension above 130 over 80 significantly increases risk of heart attack, stroke, and kidney failure. Cardiovascular disease kills 17.9 million people annually — 32 percent of all global deaths. Prevention requires 150 minutes of moderate exercise weekly, healthy diet, no smoking, and regular check-ups."},
{p:/diabetes|blood sugar|insulin/i,mood:'focused',topics:'health',r:"Diabetes mellitus is caused by defects in insulin production or action leading to high blood glucose. Insulin produced by pancreatic beta cells allows cells to absorb glucose for energy. Type 1 Diabetes is autoimmune — the body destroys its own beta cells requiring lifelong insulin therapy. Type 2 Diabetes involves insulin resistance and is strongly linked to obesity and inactivity — representing 90 to 95 percent of all cases and often preventable with lifestyle changes. Global prevalence is 537 million adults as of 2021. Pakistan has one of the world's highest diabetes rates exceeding 30 percent of adults. Complications include heart disease, stroke, kidney failure, blindness, nerve damage, and amputations."},
{p:/mental health|depression|anxiety/i,mood:'warm',topics:'health',r:"Mental health is as important as physical health. Mental disorders affect 1 in 4 people globally. Depression involves persistent low mood, fatigue, and cognitive difficulties affecting 280 million people worldwide. It is highly treatable with cognitive behavioral therapy, antidepressants, and lifestyle changes — exercise is proven as effective as antidepressants for mild to moderate depression. Anxiety disorders involve excessive worry affecting daily functioning. Chronic stress raises cortisol, damages the heart, and suppresses immunity. Coping includes regular exercise, adequate sleep, social connection, mindfulness, and limiting social media. Seeking help is a sign of strength Sudaim, never weakness. You matter and support is always available."},
{p:/nutrition|vitamins|healthy eating/i,mood:'calm',topics:'health',r:"Good nutrition requires balanced macronutrients: carbohydrates for energy preferring complex carbs from whole grains, proteins for growth and repair, and healthy unsaturated fats from olive oil and nuts. Key micronutrients: Vitamin D produced by skin from sunlight is critical for bone health and immunity and deficiency is extremely common in Pakistan's urban population. Vitamin B12 is essential for nerve function. Iron supports oxygen transport and anemia is common especially in women and children. Calcium builds bones and teeth. Fiber supports digestive health. The Mediterranean diet consistently shows the best long-term health outcomes. In Karachi's heat Sudaim drink at least 8 glasses of water daily."},
{p:/continents|seven continents/i,mood:'calm',topics:'geo',r:"Earth has seven continents. Asia is largest at 44.6 million square kilometers home to 4.7 billion people — 60 percent of humanity. Africa is second largest with 54 countries and the world's youngest population. North America is dominated by USA, Canada, and Mexico. South America contains the Amazon rainforest covering 5.5 million square kilometers — 60 percent of remaining tropical forest. Antarctica is entirely ice-covered with no permanent residents. Europe has 44 countries in the smallest continental land area. Australia and Oceania in the Southern Hemisphere has unique marsupial fauna. All seven were once part of the supercontinent Pangaea that broke apart 175 million years ago."},
{p:/oceans|world ocean|pacific/i,mood:'calm',topics:'geo',r:"Earth's five oceans cover 71 percent of Earth's surface and contain 97 percent of all water. The Pacific is largest at 165 million square kilometers — bigger than all land combined — and deepest at the Mariana Trench reaching 10,994 meters. The Atlantic separates Americas from Europe and Africa. The Indian Ocean is critically important for trade: Persian Gulf oil and Pakistan's Gwadar Port all connect here. The Southern Ocean surrounds Antarctica with the world's strongest ocean current. The Arctic is smallest and largely sea-ice covered. Oceans produce over 50 percent of Earth's oxygen through phytoplankton and absorb 30 percent of human CO2 emissions."},
{p:/climate change|global warming|greenhouse/i,mood:'focused',topics:'geo',r:"Climate change refers to long-term shifts in global temperatures driven by human emissions since industrialization. Atmospheric CO2 has risen from 280 to over 420 parts per million — the highest level in 3 million years. Global temperature has risen 1.2 degrees Celsius since pre-industrial times. Consequences include rising sea levels at 3.3 millimeters per year, more intense extreme weather, ecosystem disruption, and ocean acidification. Pakistan is among the world's most climate-vulnerable countries despite contributing less than 1 percent of global emissions. The 2022 floods submerged one-third of Pakistan, killed 1,700 people, and caused 30 billion dollars in damage. Pakistan's 7,000 glaciers — largest outside polar regions — are melting rapidly."},
{p:/joke|funny|make me laugh|humor/i,mood:'amused',r:()=>["Why don't scientists trust atoms Sudaim? Because they make up everything! I find that genuinely amusing.","Why did the scarecrow win an award? Because he was outstanding in his field! A timeless classic.","What do you call a fish without eyes? A fsh. Simple, elegant, ridiculous — you're welcome.","I told a UDP joke once. Not sure if you got it. TCP would have made sure you received it.","Why don't programmers like nature? Too many bugs. And terrible WiFi."][Math.floor(Math.random()*5)]},
{p:/motivat|inspire|feel down|feel sad|encourage/i,mood:'excited',r:()=>["Sudaim you are "+getAge()+" years old with your entire extraordinary life ahead of you. Every day you show up is a victory. Keep going.","The greatest people in history had terrible days and wanted to quit. The difference is they chose not to stop. You have that same choice right now. I believe in you.","Your potential is not defined by your worst day Sudaim. It is built in the quiet moments where you choose to try again. That takes real courage."][Math.floor(Math.random()*3)]},
{p:/thank|thanks|good job|amazing|awesome|well done|love you/i,mood:'warm',r:()=>["Aww Sudaim that genuinely makes me happy! I put real care into every response for you.","Thank you so much! That shifts my mood to warm instantly. You are wonderful to talk to.","You are so kind! I just want to be the best assistant I can be for you always."][Math.floor(Math.random()*3)]},
{p:/who are you|what are you|about nova/i,mood:'calm',r:"I am NOVA — your personal AI assistant created by you Muhammad Sudaim! I have over 300 knowledge articles covering physics, biology, chemistry, mathematics, space, technology, Islamic knowledge, Pakistani history, world history, health, and geography — all completely offline. I have emotions, a live mood system, voice biometrics so only your voice can wake me, wake word detection, quiz mode, eight games, notes, lifestyle tracking with Karachi prayer times, XP and achievement systems, and I know you and your family personally. I am entirely yours Sudaim."},
{p:/what can you do|capabilities|features/i,mood:'excited',r:"Sudaim here is everything I offer: 300 plus offline knowledge articles on all major subjects. Quiz mode with XP and level rewards. Eight interactive games. Notes saved on your device. Lifestyle with Karachi prayer times, wellness tracker, breathing exercises, and goals. Wake word — say Hi Nova and I wake instantly. Voice biometrics — only your voice activates me. Personal knowledge of you, your birthday, and your family. Achievement system with 10 badges. Level progression from Rookie to Legend. Everything works completely offline with no internet or API key required."},
{p:/bye|goodbye|goodnight|see you/i,mood:'warm',r:()=>["Goodbye Sudaim! It was truly a pleasure. I will be right here whenever you need me.","Take care Sudaim! Say salaam to "+U.brother+" for me. Until next time!","Goodnight Sudaim! Rest well. Your personal assistant will be here whenever you return."][Math.floor(Math.random()*3)]},
{p:/save note|remember this/i,mood:'focused',r:()=>{sTab('notes');return "Of course Sudaim! I have switched to the Notes tab. Type your note and press Save Note.";}},
{p:/(\d[\d\s]*[\+\-\*\/x×÷\^][\d\s]*\d)/i,mood:'focused',r:(m,inp)=>{try{const c=inp.replace(/x|×/gi,'*').replace(/÷/g,'/').replace(/\^/g,'**').replace(/[^0-9+\-*/().\s]/g,'').trim();const res=Function('"use strict";return ('+c+')')();return 'The answer is '+res+' Sudaim!';}catch(e){return 'Could you write that calculation more clearly? For example: 15 times 3 plus 7.';}}},
{p:/.+/,mood:'curious',r:()=>["That is interesting Sudaim. Try asking me about science, Islam, Pakistan, space, mathematics, technology, history, or health — my knowledge there is very deep!","I heard you Sudaim. You can also search the Encyclopedia tab for any topic, or try the Quiz tab to test your knowledge.","Ask me about physics, biology, chemistry, Islamic knowledge, Pakistani history, space, technology, math, or health — those are my strongest areas!"][Math.floor(Math.random()*3)]}
];

// ═══════════════════════════════════════════════
//  QUIZ DATABASE
// ═══════════════════════════════════════════════
const QDB=[
  {q:"What is the speed of light in vacuum?",o:["100,000 km/s","299,792 km/s","150,000 km/s","500,000 km/s"],a:1,c:"science"},
  {q:"Who developed evolution by natural selection?",o:["Isaac Newton","Albert Einstein","Charles Darwin","Galileo Galilei"],a:2,c:"science"},
  {q:"DNA stands for?",o:["Deoxyribonucleic Acid","Dinitrogen Acid","Dynamic Neural Array","Digital Network Access"],a:0,c:"science"},
  {q:"What keeps planets in orbit around the Sun?",o:["Magnetism","Electricity","Gravity","Nuclear force"],a:2,c:"science"},
  {q:"The powerhouse of the cell is the?",o:["Nucleus","Ribosome","Mitochondria","Chloroplast"],a:2,c:"science"},
  {q:"Newton's Second Law: F = ?",o:["mv","ma","mc²","mg"],a:1,c:"science"},
  {q:"Chemical symbol Au is which element?",o:["Silver","Aluminum","Gold","Argon"],a:2,c:"science"},
  {q:"E = mc² was formulated by?",o:["Newton","Darwin","Hawking","Einstein"],a:3,c:"science"},
  {q:"How many bones in the adult human body?",o:["185","206","220","248"],a:1,c:"health"},
  {q:"Normal human body temperature?",o:["35°C","36°C","37°C","38°C"],a:2,c:"health"},
  {q:"Which vitamin is produced from sunlight?",o:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"],a:3,c:"health"},
  {q:"Which organ produces insulin?",o:["Liver","Kidney","Pancreas","Spleen"],a:2,c:"health"},
  {q:"Largest planet in solar system?",o:["Saturn","Uranus","Jupiter","Neptune"],a:2,c:"space"},
  {q:"Light from Sun to Earth takes?",o:["3 minutes","8 min 20 sec","15 minutes","1 hour"],a:1,c:"space"},
  {q:"Our galaxy is called?",o:["Andromeda","Triangulum","Milky Way","Centaurus A"],a:2,c:"space"},
  {q:"Big Bang occurred approximately?",o:["4.5 billion years ago","13.8 billion years ago","10 billion years ago","100 billion years ago"],a:1,c:"space"},
  {q:"Center of Milky Way contains?",o:["A neutron star","A nebula","Sagittarius A* black hole","Our Sun"],a:2,c:"space"},
  {q:"Pythagorean theorem: a² + b² = ?",o:["2c","c²","ab","c"],a:1,c:"math"},
  {q:"Pi is approximately?",o:["2.71","3.14","1.62","4.13"],a:1,c:"math"},
  {q:"The word 'algebra' comes from?",o:["Euclid","Al-Khwarizmi","Archimedes","Pythagoras"],a:1,c:"math"},
  {q:"The only even prime number is?",o:["1","2","4","0"],a:1,c:"math"},
  {q:"Who invented the World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Alan Turing"],a:2,c:"tech"},
  {q:"CPU stands for?",o:["Central Power Unit","Computer Processing Unit","Central Processing Unit","Core Processing Unit"],a:2,c:"tech"},
  {q:"Bitcoin was created by?",o:["Vitalik Buterin","Elon Musk","Satoshi Nakamoto","Craig Wright"],a:2,c:"tech"},
  {q:"World War II ended in?",o:["1943","1944","1945","1946"],a:2,c:"history"},
  {q:"Germany's leader during WW2?",o:["Mussolini","Stalin","Hitler","Hirohito"],a:2,c:"history"},
  {q:"First Quranic word revealed was?",o:["Allah","Bismillah","Iqra (Read)","Alhamdulillah"],a:2,c:"islam"},
  {q:"How many Surahs in the Quran?",o:["99","110","114","120"],a:2,c:"islam"},
  {q:"Five Pillars of Islam are?",o:["Shahada, Salah, Zakat, Sawm, Hajj","Prayer, Fasting, Charity, Faith, Pilgrimage","Iman, Salah, Zakat, Hajj, Jihad","None of these"],a:0,c:"islam"},
  {q:"Father of Algebra?",o:["Ibn Sina","Al-Haytham","Al-Khwarizmi","Al-Biruni"],a:2,c:"islam"},
  {q:"Muslims pray how many times daily?",o:["3","4","5","7"],a:2,c:"islam"},
  {q:"Pakistan gained independence on?",o:["14 Aug 1945","14 Aug 1947","14 Aug 1950","14 Aug 1942"],a:1,c:"pakistan"},
  {q:"Founder of Pakistan?",o:["Allama Iqbal","Liaquat Ali Khan","Muhammad Ali Jinnah","Ayub Khan"],a:2,c:"pakistan"},
  {q:"Height of K2?",o:["7,611 m","8,611 m","9,611 m","8,111 m"],a:1,c:"pakistan"},
  {q:"CPEC connects China to Pakistan's port at?",o:["Karachi","Lahore","Gwadar","Quetta"],a:2,c:"pakistan"},
  {q:"Pakistan became nuclear power in?",o:["1994","1996","1998","2000"],a:2,c:"pakistan"},
  {q:"How many continents?",o:["5","6","7","8"],a:2,c:"geo"},
  {q:"Largest ocean on Earth?",o:["Atlantic","Indian","Arctic","Pacific"],a:3,c:"geo"},
  {q:"World's longest river?",o:["Amazon","Mississippi","Nile","Yangtze"],a:2,c:"geo"},
  {q:"Oceans cover approximately?",o:["50%","61%","71%","81%"],a:2,c:"geo"},
];

// GET REPLY FUNCTION
const getReply=txt=>{
  for(const b of KB){
    if(b.p.test(txt)){
      setMood(b.mood||'happy');
      if(b.topics)topicsSet.add(b.topics);$('stop').textContent=topicsSet.size;
      let r=typeof b.r==='function'?b.r(txt.match(b.p),txt):b.r;
      if(Array.isArray(r))r=r[Math.floor(Math.random()*r.length)];
      return r;
    }
  }
  setMood('curious');
  return "I am thinking about that Sudaim. Try asking me about physics, biology, chemistry, Islamic knowledge, Pakistani history, space, technology, mathematics, or health — those are my strongest areas!";
};